### ISSUE TITLE
halo mastah 🗿

### ISSUE THREAD

**Issue by ridho17-ind** [inirey/whatsapp-bot#58]
mau coba deploy ni

**Comment by ridho17-ind** [comment]
ini naroh session dimana banh

**Comment by erzacanz** [comment]
> ini naroh session dimana banh

session.data.json

**Comment by ridho17-ind** [comment]
gada bang

**Comment by ridho17-ind** [comment]
> 

gada bg

**Comment by inirey** [comment]
> > 
> 
> gada bg

Buat dumlu bang

**Comment by ridho17-ind** [comment]
> > > 
> > 
> > 
> > gada bg
> 
> Buat dumlu bang

anu bang udah tp crash
