### ISSUE TITLE
ask

### ISSUE THREAD

**Issue by natxdixie** [inirey/whatsapp-bot#63]
bang ane run di heroku procfile
worker: node . kok engror ya down malah

**Comment by botstylee** [comment]
> bang ane run di heroku procfile worker: node . kok engror ya down malah

Lo Gonta ganti Sc Mulu dh

**Comment by natxdixie** [comment]
> > bang ane run di heroku procfile worker: node . kok engror ya down malah
> 
> Lo Gonta ganti Sc Mulu dh

aowkwk nyoba² doang :v

**Comment by inirey** [comment]
> bang ane run di heroku procfile worker: node . kok engror ya down malah

Coba lagi bang baru ane fix tadi
